"""
Localization module for Quiz Examination System
Supports English and Azerbaijani languages
"""

# Translation dictionaries
TRANSLATIONS = {
    'en': {
        # Common
        'app_name': 'Quiz Examination System',
        'welcome': 'Welcome',
        'save': 'Save',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'edit': 'Edit',
        'add': 'Add',
        'close': 'Close',
        'search': 'Search',
        'filter': 'Filter',
        'export': 'Export',
        'import': 'Import',
        'submit': 'Submit',
        'back': 'Back',
        'next': 'Next',
        'previous': 'Previous',
        'yes': 'Yes',
        'no': 'No',
        'loading': 'Loading...',
        'success': 'Success',
        'error': 'Error',
        'warning': 'Warning',
        'info': 'Info',
        'confirm': 'Confirm',
        'download': 'Download',
        'upload': 'Upload',
        'view': 'View',
        'details': 'Details',
        'all': 'All',
        'active': 'Active',
        'inactive': 'Inactive',
        'status': 'Status',
        'actions': 'Actions',
        'refresh': 'Refresh',
        'clear': 'Clear',
        'reset': 'Reset',
        'update': 'Update',
        'create': 'Create',
        'send': 'Send',
        'test': 'Test',
        'preview': 'Preview',

        # Login
        'login': 'Login',
        'logout': 'Logout',
        'please_sign_in': 'Please sign in to continue',
        'username_or_email': 'Username or Email',
        'password': 'Password',
        'signing_in': 'Signing in...',
        'invalid_credentials': 'Invalid username or password',
        'enter_credentials': 'Please enter both username and password',
        'session_failed': 'Failed to create session',

        # Dashboard
        'dashboard': 'Dashboard',
        'admin_dashboard': 'Admin Dashboard',
        'examinee_dashboard': 'Examinee Dashboard',
        'statistics': 'Statistics',
        'overview': 'Overview',
        'quick_actions': 'Quick Actions',
        'recent_activity': 'Recent Activity',
        'system_stats': 'System Statistics',

        # Users
        'users': 'Users',
        'user_management': 'User Management',
        'manage_users': 'Manage Users',
        'add_user': 'Add User',
        'edit_user': 'Edit User',
        'delete_user': 'Delete User',
        'username': 'Username',
        'email': 'Email',
        'full_name': 'Full Name',
        'role': 'Role',
        'department': 'Department',
        'unit': 'Unit',
        'employee_id': 'Employee ID',
        'admin': 'Admin',
        'examinee': 'Examinee',
        'expert': 'Expert',
        'hr': 'HR',
        'total_users': 'Total Users',
        'active_users': 'Active Users',
        'user_created': 'User created successfully',
        'user_updated': 'User updated successfully',
        'user_deleted': 'User deleted successfully',
        'user_activated': 'User activated successfully',
        'user_deactivated': 'User deactivated successfully',
        'search_users': 'Search users by name, username, or email',
        'filter_by_role': 'Filter by Role',
        'filter_by_status': 'Filter by Status',
        'no_users_found': 'No users found',
        'create_user_account': 'Create User Account',
        'enter_username': 'Enter username',
        'enter_email': 'Enter email address',
        'enter_full_name': 'Enter full name',
        'enter_password': 'Enter password',
        'select_role': 'Select role',
        'select_department': 'Select department',
        'select_unit': 'Select unit',
        'username_required': 'Username is required',
        'email_required': 'Email is required',
        'password_required': 'Password is required',
        'full_name_required': 'Full name is required',
        'role_required': 'Role is required',

        # Exams
        'exams': 'Exams',
        'exam_management': 'Exam Management',
        'manage_exams': 'Manage Exams',
        'add_exam': 'Add Exam',
        'create_exam': 'Create Exam',
        'edit_exam': 'Edit Exam',
        'delete_exam': 'Delete Exam',
        'exam_title': 'Exam Title',
        'exam_description': 'Exam Description',
        'exam_category': 'Exam Category',
        'duration': 'Duration',
        'duration_minutes': 'Duration (minutes)',
        'passing_score': 'Passing Score',
        'passing_score_percent': 'Passing Score (%)',
        'max_attempts': 'Max Attempts',
        'randomize_questions': 'Randomize Questions',
        'show_results': 'Show Results',
        'start_date': 'Start Date',
        'end_date': 'End Date',
        'total_exams': 'Total Exams',
        'active_exams': 'Active Exams',
        'exam_created': 'Exam created successfully',
        'exam_updated': 'Exam updated successfully',
        'exam_deleted': 'Exam deleted successfully',
        'exam_activated': 'Exam activated successfully',
        'exam_deactivated': 'Exam deactivated successfully',
        'search_exams': 'Search exams',
        'no_exams_found': 'No exams found',
        'available_exams': 'Available Exams',
        'assignment_name': 'Assignment Name',
        'assignment': 'Assignment',
        'completion': 'Completion',
        'pdf_variants': 'PDF Variants',
        'select_preset': 'Select Preset',
        'select_exam_templates': 'Select Exam Templates',
        'use_preset_template': 'Use Preset Template',
        'select_exam_templates_manually': 'Select Exam Templates Manually',
        'select_users': 'Select Users',
        'select_departments': 'Select Departments',
        'assign_department': 'Assign Department',
        'assign_unit': 'Assign Unit',
        'online_exam': 'Online Exam',
        'user_already_exists': 'User already exists',
        'my_exams': 'My Exams',
        'take_exam': 'Take Exam',
        'start_exam': 'Start Exam',
        'resume_exam': 'Resume Exam',
        'exam_in_progress': 'Exam in Progress',
        'exam_completed': 'Exam Completed',
        'exam_details': 'Exam Details',
        'questions_count': 'Questions',
        'time_limit': 'Time Limit',
        'attempts_left': 'Attempts Left',
        'minutes': 'minutes',
        'enter_exam_title': 'Enter exam title',
        'enter_exam_description': 'Enter exam description',
        'select_category': 'Select category',
        'exam_settings': 'Exam Settings',
        'basic_info': 'Basic Information',
        'advanced_settings': 'Advanced Settings',
        'security_settings': 'Security Settings',
        'question_pool': 'Question Pool',
        'use_question_pool': 'Use Question Pool',
        'enable_fullscreen': 'Enable Fullscreen',
        'prevent_focus_loss': 'Prevent Focus Loss',
        'enable_logging': 'Enable Logging',
        'enable_pattern_analysis': 'Enable Pattern Analysis',

        # Questions
        'questions': 'Questions',
        'question_management': 'Question Management',
        'manage_questions': 'Manage Questions',
        'add_question': 'Add Question',
        'edit_question': 'Edit Question',
        'delete_question': 'Delete Question',
        'question_text': 'Question Text',
        'question_type': 'Question Type',
        'multiple_choice': 'Multiple Choice',
        'true_false': 'True/False',
        'short_answer': 'Short Answer',
        'essay': 'Essay',
        'correct_answer': 'Correct Answer',
        'explanation': 'Explanation',
        'points': 'Points',
        'difficulty': 'Difficulty',
        'difficulty_level': 'Difficulty Level',
        'easy': 'Easy',
        'medium': 'Medium',
        'hard': 'Hard',
        'total_questions': 'Total Questions',
        'question_created': 'Question created successfully',
        'question_updated': 'Question updated successfully',
        'question_deleted': 'Question deleted successfully',
        'search_questions': 'Search questions',
        'no_questions_found': 'No questions found',
        'question_options': 'Question Options',
        'add_option': 'Add Option',
        'option_text': 'Option Text',
        'is_correct': 'Is Correct',
        'select_question_type': 'Select question type',
        'enter_question_text': 'Enter question text',
        'enter_correct_answer': 'Enter correct answer',
        'enter_explanation': 'Enter explanation (optional)',
        'upload_image': 'Upload Image',
        'question_image': 'Question Image',
        'bulk_import': 'Bulk Import',
        'import_questions': 'Import Questions',
        'select_file': 'Select File',
        'import_from_csv': 'Import from CSV/Excel',
        'questions_imported': 'Questions imported successfully',
        'import_failed': 'Import failed',
        'question_bank': 'Question Bank',
        'observers': 'Observers',
        'manage_observers': 'Manage Observers',
        'observer_instructions': 'Observers can view this topic and its questions but cannot make changes.',
        'select_observer': 'Select Observer',
        'add_observer': 'Add Observer',
        'current_observers': 'Current Observers',
        'no_observers_assigned': 'No observers assigned yet',
        'observer_added': 'Observer added successfully',
        'observer_removed': 'Observer removed',
        'observer_already_assigned': 'Observer already has access',
        'observer_select_prompt': 'Please select an observer to add',
        'observer_manage_forbidden': 'Only the topic owner or admins can manage observers',

        # Grading
        'grading': 'Grading',
        'grade_exam': 'Grade Exam',
        'pending_grading': 'Pending Grading',
        'graded': 'Graded',
        'grade': 'Grade',
        'score': 'Score',
        'student_answer': 'Student Answer',
        'points_earned': 'Points Earned',
        'total_points': 'Total Points',
        'grading_completed': 'Grading completed successfully',
        'auto_graded': 'Auto-Graded',
        'manual_grading_required': 'Manual Grading Required',

        # Results
        'results': 'Results',
        'exam_results': 'Exam Results',
        'my_results': 'My Results',
        'view_results': 'View Results',
        'results_history': 'Results History',
        'passed': 'Passed',
        'failed': 'Failed',
        'pending': 'Pending',
        'not_passed': 'Not Passed',
        'your_score': 'Your Score',
        'total_score': 'Total Score',
        'correct_answers': 'Correct Answers',
        'incorrect_answers': 'Incorrect Answers',
        'unanswered': 'Unanswered',
        'time_taken': 'Time Taken',
        'exam_date': 'Exam Date',
        'attempt': 'Attempt',
        'no_results': 'No results available',
        'congratulations': 'Congratulations!',
        'you_passed': 'You passed the exam',
        'you_failed': 'Unfortunately, you did not pass',
        'try_again': 'Try Again',

        # Reports
        'reports': 'Reports',
        'analytics': 'Analytics',
        'exam_report': 'Exam Report',
        'user_report': 'User Report',
        'generate_report': 'Generate Report',
        'export_pdf': 'Export PDF',
        'export_excel': 'Export Excel',
        'export_csv': 'Export CSV',
        'report_generated': 'Report generated successfully',
        'no_data': 'No data available',
        'average_score': 'Average Score',
        'highest_score': 'Highest Score',
        'lowest_score': 'Lowest Score',
        'pass_rate': 'Pass Rate',
        'completion_rate': 'Completion Rate',
        'attempts_count': 'Total Attempts',

        # Settings
        'settings': 'Settings',
        'system_settings': 'System Settings',
        'exam_settings_label': 'Exam Settings',
        'language_settings': 'Language Settings',
        'system_language': 'System Language',
        'language': 'Language',
        'select_language': 'Select system language',
        'language_changed': 'Language changed successfully',
        'settings_updated': 'Settings updated successfully',
        'settings_failed': 'Failed to save settings',
        'default_exam_duration': 'Default Exam Duration',
        'default_duration_minutes': 'Exam Duration (minutes)',
        'set_passing_score': 'Set the minimum score required to pass exams',
        'set_exam_duration': 'Set the default time limit for exams',
        'change_language': 'Change the language used throughout the system',
        'save_passing_score': 'Save Passing Score',
        'save_exam_duration': 'Save Exam Duration',
        'save_language': 'Save Language',
        'passing_score_updated': 'Passing score updated to {value}%',
        'exam_duration_updated': 'Exam duration updated to {value} minutes',
        'passing_score_range': 'Passing score must be between 0 and 100',
        'duration_positive': 'Exam duration must be greater than 0',
        'enter_valid_number': 'Please enter a valid number',
        'students_need_score': 'Students need this score to pass exams',
        'default_time_limit': 'Default time limit for exams',

        # Email
        'email': 'Email',
        'email_templates': 'Email Templates',
        'customize_email': 'Customize email notifications for exam results',
        'template_type': 'Template Type',
        'template_language': 'Template Language',
        'passed_results': 'Passed Results',
        'failed_results': 'Failed Results',
        'pending_grading': 'Pending Grading',
        'email_subject': 'Email Subject',
        'email_body': 'Email Body',
        'save_template': 'Save Template',
        'reset_to_default': 'Reset to Default',
        'test_email': 'Test Email',
        'template_saved': 'Template saved successfully',
        'template_reset': 'Template reset to default',
        'template_not_found': 'Default template not found',
        'test_email_opened': 'Test email opened for {email}',
        'email_failed': 'Failed to open email client',
        'available_placeholders': 'Available Placeholders',
        'subject_body_required': 'Subject and body cannot be empty',
        'enter_subject_body': 'Please enter both subject and body before testing',

        # Profile
        'profile': 'Profile',
        'my_profile': 'My Profile',
        'edit_profile': 'Edit Profile',
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'password_updated': 'Password updated successfully',
        'password_mismatch': 'Passwords do not match',
        'incorrect_password': 'Current password is incorrect',
        'profile_updated': 'Profile updated successfully',

        # Exam Interface
        'exam_interface': 'Exam Interface',
        'time_remaining': 'Time Remaining',
        'question': 'Question',
        'of': 'of',
        'mark_for_review': 'Mark for Review',
        'marked_for_review': 'Marked for Review',
        'answered': 'Answered',
        'not_answered': 'Not Answered',
        'submit_exam': 'Submit Exam',
        'confirm_submit': 'Are you sure you want to submit?',
        'confirm_submit_message': 'You will not be able to change your answers after submission.',
        'exam_submitted': 'Exam submitted successfully',
        'your_answer': 'Your Answer',
        'select_answer': 'Select your answer',
        'type_answer': 'Type your answer',
        'true': 'True',
        'false': 'False',
        'navigation': 'Navigation',
        'save_continue': 'Save & Continue',
        'skip_question': 'Skip Question',
        'exam_auto_submit': 'Time is up! The exam will be submitted automatically.',
        'time_warning': 'Warning: Only {minutes} minutes remaining!',

        # Permissions
        'permissions': 'Permissions',
        'assign_exam': 'Assign Exam',
        'exam_permissions': 'Exam Permissions',
        'grant_access': 'Grant Access',
        'revoke_access': 'Revoke Access',
        'access_granted': 'Access granted successfully',
        'access_revoked': 'Access revoked successfully',
        'assigned_users': 'Assigned Users',
        'available_users': 'Available Users',

        # View Switcher
        'switch_view': 'Switch View',
        'admin_view': 'Admin View',
        'expert_view': 'Expert View',
        'hr_view': 'HR View',
        'examinee_view': 'Examinee View',

        # Roles
        'admin_role': 'Administrator',
        'expert_role': 'Expert',
        'hr_role': 'HR Manager',
        'examinee_role': 'Examinee',

        # Validation Messages
        'field_required': 'This field is required',
        'invalid_email': 'Invalid email address',
        'invalid_format': 'Invalid format',
        'value_too_short': 'Value is too short',
        'value_too_long': 'Value is too long',
        'invalid_number': 'Invalid number',
        'invalid_date': 'Invalid date',

        # Confirmations
        'are_you_sure': 'Are you sure?',
        'cannot_undo': 'This action cannot be undone',
        'confirm_delete': 'Are you sure you want to delete this item?',
        'confirm_delete_user': 'Are you sure you want to delete this user?',
        'confirm_delete_exam': 'Are you sure you want to delete this exam?',
        'confirm_delete_question': 'Are you sure you want to delete this question?',

        # Notifications
        'operation_successful': 'Operation completed successfully',
        'operation_failed': 'Operation failed',
        'changes_saved': 'Changes saved successfully',
        'changes_discarded': 'Changes discarded',
        'no_changes': 'No changes to save',

        # Date/Time
        'today': 'Today',
        'yesterday': 'Yesterday',
        'tomorrow': 'Tomorrow',
        'date': 'Date',
        'time': 'Time',
        'datetime': 'Date & Time',
        'created_at': 'Created At',
        'updated_at': 'Updated At',
        'last_login': 'Last Login',

        # Categories
        'category': 'Category',
        'categories': 'Categories',
        'uncategorized': 'Uncategorized',

        # PDF Export
        'pdf_export': 'PDF Export',
        'export_variants': 'Export Variants',
        'variant_count': 'Variant Count',
        'generate_pdf': 'Generate PDF',
        'pdf_generated': 'PDF generated successfully',
        'pdf_failed': 'PDF generation failed',

        # Additional Question Management
        'select_exam': 'Select an exam to view question pool statistics',
        'select_topic': 'Select Topic',
        'filter_by_type': 'Filter by Type',
        'all_types': 'All Types',
        'image': 'Image',
        'download_template': 'Download Template',
        'export_questions': 'Export Questions',
        'new_topic': 'New Topic',
        'question_pool_config': 'Question Pool Configuration',
        'question_bank_overview': 'Question Bank Overview',
        'not_used': 'Not used',
        'test_dialog': 'Test Dialog',
        'add_new_question': 'Add New Question',
        'question_text_required': 'Question text is required',
        'valid_numeric': 'Please enter valid numeric values',
        'add_option_text': 'Add Option',
        'correct': 'Correct',
        'short_answer_question': 'Short Answer Question',
        'essay_question': 'Essay Question',
        'sample_answers': 'Provide sample answers or keywords for grading reference',
        'click_to_view': 'Click image to view full size',
        'answer_options': 'Answer Options',
        'question_preview': 'Question Preview',
        'confirm_delete_title': 'Confirm Delete',
        'select_questions_file': 'Select Questions File',
        'no_file_selected': 'No file selected',
        'template_downloaded': 'Template Downloaded',
        'no_questions_found_exam': 'No questions found in this exam',
        'questions_exported_title': 'Questions Exported',
        'importing_questions': 'Importing Questions',
        'import_successful': 'Import Successful',
        'import_failed_title': 'Import Failed',
        'change_image': 'Change Image',
        'remove_image': 'Remove Image',
        'no_image_selected': 'No image selected',
        'upload_image_btn': 'Upload Image',
        'select_question_image': 'Select Question Image',
        'question_image_title': 'Question Image',
        'edit_topic': 'Edit Topic',
        'enter_descriptive_title': 'Enter a descriptive exam title',
        'provide_instructions': 'Provide exam instructions or description',
        'exam_title_required': 'Exam title is required',
        'please_select_exam': 'Please select an exam first',
        'please_select_exam_questions': 'Please select an exam to view questions',
        'view_question': 'View Question',
        'edit_question_tooltip': 'Edit Question',
        'delete_question_tooltip': 'Delete Question',
        'number_symbol': '#',
        'english': 'English',
        'azerbaijani': 'Azərbaycan dili',
        'explanation_optional': 'Explanation (optional)',
        'sample_answer_label': 'Sample Answer / Keywords (Optional)',
        'pool_ready': 'Pool Ready',
        'pool_issue': 'Pool Configuration Issue',
        'points_greater_zero': 'Points must be greater than 0',
        'error_saving_question': 'Error saving question: {}',
        'error_uploading_image': 'Error uploading image: {}',
        'file_size_too_large': 'File size too large (max {0}MB)',
        'invalid_file_type': 'Invalid file type. Please select a JPG, PNG, or GIF image',
        'short_answer_help': 'Students will type a brief text response',
        'essay_help': 'Students will write a longer text response',
        'will_select_questions': 'Will select {0} questions from {1} available',
        'available_count': '{0} available',
        'requested_available': '{0}/{1}',
        'no_questions_found_exam_msg': 'No questions found for this exam',

        # Quiz Management
        'create_assignment': 'Create Assignment',
        'manage_presets': 'Manage Presets',
        'view_archived': 'View Archived',
        'assignment_management': 'Assignment Management',
        'topic_title_required': 'Topic title is required',
        'generating_pdfs': 'Generating PDFs...',
        'pdfs_generated_successfully': 'PDFs Generated Successfully!',
        'open_folder': 'Open Folder',
        'export_assignment': 'Export Assignment as PDF',
        'variants_configured': 'Variants configured',
        'this_will_generate': 'This will generate:',
        'exam_paper': 'Exam paper for each variant',
        'answer_key': 'Answer key for each variant',

        # Reports
        'score_distribution': 'Score Distribution',
        'pass_fail_trend': 'Pass/Fail Rate Trend',
        'question_difficulty_analysis': 'Question Difficulty Analysis',
        'exam_performance': 'Exam Performance',
        'user_progress': 'User Progress',
        'question_analysis': 'Question Analysis',
        'detailed_analysis': 'Detailed analysis of exam performance',
        'individual_tracking': 'Individual user performance tracking',
        'difficulty_performance': 'Question difficulty and performance metrics',
        'key_performance_indicators': 'Key Performance Indicators',
        'performance_analytics': 'Performance Analytics',
        'detailed_reports': 'Detailed Reports',
        'export_by_exam': 'Export by Exam',
        'export_by_student': 'Export by Student',
        'select_student': 'Select Student',
        'choose_student': 'Choose a student',
        'choose_exam': 'Choose an exam',
        'generate_pdf_report': 'Generate PDF Report',
        'filter_by_topic': 'Filter by Topic',
        'filter_by_exam': 'Filter by Exam/Assignment',
        'export_user_data': 'Export User Data',

        # Additional
        'scheduled': 'Scheduled',
        'deadline': 'Deadline',
        'shortcuts': 'Shortcuts',
        'student': 'Student',
        'submitted': 'Submitted',
        'completed': 'Completed',
        'retake': 'Retake',
        'not_specified': 'Not specified',

        # Reports - Additional
        'avg_exam_scores_over_time': 'Average Exam Scores Over Time',
        'pass_rate_trend_over_time': 'Pass Rate Trend Over Time',
        'success_rate_by_difficulty': 'Success Rate by Question Difficulty',
        'success_rate': 'Success Rate',
        'sessions': 'Sessions',
        'min_score': 'Min Score',
        'max_score': 'Max Score',
        'avg_duration_min': 'Avg Duration (min)',
        'exam_sessions': 'Exam Sessions',
        'best_score': 'Best Score',
        'avg_duration': 'Avg Duration',
        'last_activity': 'Last Activity',
        'total_answers': 'Total Answers',
        'correct': 'Correct',
        'showing_questions_min_answers': 'Showing questions with at least 3 answers for statistical reliability',
        'showing_all_questions': 'Showing all questions (including those with less than 3 answers)',
        'questions_low_success_review': 'Questions with less than 60% success rate may need review',
        'all_topics': 'All Topics',
        'correct_answer': 'Correct Answer',
        'user_answer': 'User Answer',
        'wrong': 'Wrong',
        'correct_total': 'Correct/Total',
        'correct_answers_count': 'Correct Answers',
        'type': 'Type',
        'result': 'Result',
        'highest_score': 'Highest Score',
        'lowest_score': 'Lowest Score',
        'total_active_exams': 'Total Active Exams',
        'total_completed_sessions': 'Total Completed Sessions',
        'worst_score': 'Worst Score',
        'all_exams_assignments': 'All Exams/Assignments',
        'departament': 'Departament',
        'exams_taken': 'Exams Taken',
        'never': 'Never',
        'showing_all_questions_including': 'Show all questions (including low-sample)',
        'create_preset_template': 'Create Preset Template',
        'changes': 'Changes',

        # PDF Export
        'export_pdf_reports': 'Export PDF Reports',
        'export_by_exam': 'Export by Exam',
        'export_by_student': 'Export by Student',
        'student_exam': "Student's Exam",
        'no_exams_for_report': 'No exams available for report generation.',
        'no_students_completed': 'No students with completed exams found.',
        'no_data_student_exam': 'No data available for student-exam reports.',
        'select_exam_generate_pdf': 'Select an exam to generate detailed PDF report with all student performances:',
        'select_student_generate_pdf': 'Select a student to generate detailed PDF report with all exam results:',
        'generate_pdf_report': 'Generate PDF Report',
        'created': 'Created',
        'legacy': 'Legacy',
        'exam_report': 'Exam Report',
        'student_report': 'Student Report',
        'generated': 'Generated',
        'performance_summary': 'Performance Summary',
        'metric': 'Metric',
        'value': 'Value',
        'total_attempts': 'Total Attempts',
        'student_performance': 'Student Performance',
        'duration_min': 'Duration (min)',
        'question_breakdown': 'Question Breakdown',
        'question_details': 'Question Details',
        'export_assignment_as_pdf': 'Export Assignment as PDF',
        'randomization_disabled': 'Randomization is disabled. All variants will be identical.',
        'generating_variants': 'Generating {0} variant(s)...',
        'assignment': 'Assignment',
        'questions': 'Questions',
        'variants_configured': 'Variants configured',
        'this_will_generate': 'This will generate:',
        'exam_paper_each_variant': 'Exam paper for each variant',
        'answer_key_each_variant': 'Answer key for each variant',
        'files': 'Files',
        'generate_pdfs': 'Generate PDFs',
        'pdfs_generated_successfully': 'PDFs Generated Successfully!',
        'variants_generated': '{0} variant(s) generated',
        'location': 'Location',
        'variant': 'Variant',
        'error_generating_pdfs': 'Error generating PDFs',
        'detailed_exam_report': 'Detailed Exam Report',
        'exam_summary': 'Exam Summary',
        'final_score': 'Final Score',
        'passing_score': 'Passing Score',
        'duration': 'Duration',
        'start_time': 'Start Time',
        'end_time': 'End Time',
        'question_by_question_breakdown': 'Question-by-Question Breakdown',
        'option': 'Option',
        'correct_answer_label': 'Correct Answer',
        'student_selected': 'Student Selected',
        'pass': 'PASS',
        'fail': 'FAIL',
        'minutes_label': 'minutes',
        'special_warning': 'SPECIAL WARNING',
        'confidential_text': 'This document contains confidential information belonging to the Space Agency of the Republic of Azerbaijan (Azercosmos).',
        'page': 'Page',
        'no_data': 'No Data',
        'no_completed_exam_session': 'No completed exam session found for this student and exam.',
        'pts': 'pts',
        'student_answer': 'Student Answer',
        'no_answer_provided': 'No answer provided',
        'correct_uppercase': 'CORRECT',
        'incorrect_uppercase': 'INCORRECT',
        'file_saved': 'File saved',
        'file_save_error': 'Error saving file',
        'save_pdf_as': 'Save PDF as',
    },

    'az': {
        # Common / Ümumi
        'app_name': 'İmtahan Sistemin',
        'welcome': 'Xoş gəlmisiniz',
        'save': 'Yadda saxla',
        'cancel': 'Ləğv et',
        'delete': 'Sil',
        'edit': 'Redaktə et',
        'add': 'Əlavə et',
        'close': 'Bağla',
        'search': 'Axtar',
        'filter': 'Süzgəc',
        'export': 'İxrac et',
        'import': 'İdxal et',
        'submit': 'Təqdim et',
        'back': 'Geri',
        'next': 'Növbəti',
        'previous': 'Əvvəlki',
        'yes': 'Bəli',
        'no': 'Xeyr',
        'loading': 'Yüklənir...',
        'success': 'Uğurlu',
        'error': 'Xəta',
        'warning': 'Xəbərdarlıq',
        'info': 'Məlumat',
        'confirm': 'Təsdiq et',
        'download': 'Yüklə',
        'upload': 'Yüklə',
        'view': 'Bax',
        'details': 'Təfərrüatlar',
        'all': 'Hamısı',
        'active': 'Aktiv',
        'inactive': 'Qeyri-aktiv',
        'status': 'Status',
        'actions': 'Əməliyyatlar',
        'refresh': 'Yenilə',
        'clear': 'Təmizlə',
        'reset': 'Sıfırla',
        'update': 'Yenilə',
        'create': 'Yarat',
        'send': 'Göndər',
        'test': 'Test',
        'preview': 'Önbaxış',

        # Login / Giriş
        'login': 'Giriş',
        'logout': 'Çıxış',
        'please_sign_in': 'Davam etmək üçün daxil olun',
        'username_or_email': 'İstifadəçi adı və ya E-poçt',
        'password': 'Şifrə',
        'signing_in': 'Daxil olunur...',
        'invalid_credentials': 'Yanlış istifadəçi adı və ya şifrə',
        'enter_credentials': 'İstifadəçi adı və şifrəni daxil edin',
        'session_failed': 'Sessiya yaradılmadı',

        # Dashboard / İdarə paneli
        'dashboard': 'İdarə paneli',
        'admin_dashboard': 'Admin paneli',
        'examinee_dashboard': 'İştirakçı paneli',
        'statistics': 'Statistika',
        'overview': 'Ümumi baxış',
        'quick_actions': 'Sürətli əməliyyatlar',
        'recent_activity': 'Son fəaliyyət',
        'system_stats': 'Sistem statistikası',

        # Users / İstifadəçilər
        'users': 'İstifadəçilər',
        'user_management': 'İstifadəçi idarəetməsi',
        'manage_users': 'İstifadəçiləri idarə et',
        'add_user': 'İstifadəçi əlavə et',
        'edit_user': 'İstifadəçini redaktə et',
        'delete_user': 'İstifadəçini sil',
        'username': 'İstifadəçi adı',
        'email': 'E-poçt',
        'full_name': 'Tam ad',
        'role': 'Rol',
        'department': 'Departament',
        'unit': 'Bölmə',
        'employee_id': 'İşçi ID',
        'admin': 'Admin',
        'examinee': 'İştirakçı',
        'expert': 'Ekspert',
        'hr': 'İK',
        'total_users': 'Ümumi istifadəçilər',
        'active_users': 'Aktiv istifadəçilər',
        'user_created': 'İstifadəçi uğurla yaradıldı',
        'user_updated': 'İstifadəçi uğurla yeniləndi',
        'user_deleted': 'İstifadəçi uğurla silindi',
        'user_activated': 'İstifadəçi uğurla aktivləşdirildi',
        'user_deactivated': 'İstifadəçi uğurla deaktivləşdirildi',
        'search_users': 'Ad, istifadəçi adı və ya e-poçta görə axtar',
        'filter_by_role': 'Rola görə süz',
        'filter_by_status': 'Statusa görə süz',
        'no_users_found': 'İstifadəçi tapılmadı',
        'create_user_account': 'İstifadəçi hesabı yarat',
        'enter_username': 'İstifadəçi adını daxil edin',
        'enter_email': 'E-poçt ünvanını daxil edin',
        'enter_full_name': 'Tam adı daxil edin',
        'enter_password': 'Şifrəni daxil edin',
        'select_role': 'Rol seçin',
        'select_department': 'Departament seçin',
        'select_unit': 'Bölmə seçin',
        'username_required': 'İstifadəçi adı tələb olunur',
        'email_required': 'E-poçt tələb olunur',
        'password_required': 'Şifrə tələb olunur',
        'full_name_required': 'Tam ad tələb olunur',
        'role_required': 'Rol tələb olunur',

        # Exams / İmtahanlar
        'exams': 'İmtahanlar',
        'exam_management': 'İmtahan idarəetməsi',
        'manage_exams': 'İmtahanları idarə et',
        'add_exam': 'İmtahan əlavə et',
        'create_exam': 'İmtahan yarat',
        'edit_exam': 'İmtahanı redaktə et',
        'delete_exam': 'İmtahanı sil',
        'exam_title': 'İmtahan başlığı',
        'exam_description': 'İmtahan təsviri',
        'exam_category': 'İmtahan kateqoriyası',
        'duration': 'Müddət',
        'duration_minutes': 'Müddət (dəqiqə)',
        'passing_score': 'Keçid balı',
        'passing_score_percent': 'Keçid balı (%)',
        'max_attempts': 'Maksimum cəhd',
        'randomize_questions': 'Sualları qarışdır',
        'show_results': 'Nəticələri göstər',
        'start_date': 'Başlama tarixi',
        'end_date': 'Bitmə tarixi',
        'total_exams': 'Ümumi imtahanlar',
        'active_exams': 'Aktiv imtahanlar',
        'exam_created': 'İmtahan uğurla yaradıldı',
        'exam_updated': 'İmtahan uğurla yeniləndi',
        'exam_deleted': 'İmtahan uğurla silindi',
        'exam_activated': 'İmtahan uğurla aktivləşdirildi',
        'exam_deactivated': 'İmtahan uğurla deaktivləşdirildi',
        'search_exams': 'İmtahan axtar',
        'no_exams_found': 'İmtahan tapılmadı',
        'available_exams': 'Mövcud imtahanlar',
        'assignment_name': 'Tapşırıq adı',
        'assignment': 'Tapşırıq',
        'completion': 'Tamamlanma',
        'pdf_variants': 'PDF variantları',
        'select_preset': 'Şablon seçin',
        'select_exam_templates': 'İmtahan şablonları seçin',
        'use_preset_template': 'Şablondan istifadə et',
        'select_exam_templates_manually': 'İmtahan şablonları əl ilə seçin',
        'select_users': 'İstifadəçilər seçin',
        'select_departments': 'Departamentlər seçin',
        'assign_department': 'Departament təyin et',
        'assign_unit': 'Bölmə təyin et',
        'online_exam': 'Onlayn imtahan',
        'user_already_exists': 'İstifadəçi artıq mövcuddur',
        'my_exams': 'Mənim imtahanlarım',
        'take_exam': 'İmtahan ver',
        'start_exam': 'İmtahana başla',
        'resume_exam': 'İmtahana davam et',
        'exam_in_progress': 'İmtahan davam edir',
        'exam_completed': 'İmtahan tamamlandı',
        'exam_details': 'İmtahan təfərrüatları',
        'questions_count': 'Suallar',
        'time_limit': 'Vaxt limiti',
        'attempts_left': 'Qalan cəhdlər',
        'minutes': 'dəqiqə',
        'enter_exam_title': 'İmtahan başlığını daxil edin',
        'enter_exam_description': 'İmtahan təsvirini daxil edin',
        'select_category': 'Kateqoriya seçin',
        'exam_settings': 'İmtahan parametrləri',
        'basic_info': 'Əsas məlumat',
        'advanced_settings': 'Əlavə parametrlər',
        'security_settings': 'Təhlükəsizlik parametrləri',
        'question_pool': 'Sual bazası',
        'use_question_pool': 'Sual bazasından istifadə et',
        'enable_fullscreen': 'Tam ekranı aktivləşdir',
        'prevent_focus_loss': 'Fokus itkisinin qarşısını al',
        'enable_logging': 'Jurnallaşdırmanı aktivləşdir',
        'enable_pattern_analysis': 'Nümunə analizini aktivləşdir',

        # Questions / Suallar
        'questions': 'Suallar',
        'question_management': 'Sual idarəetməsi',
        'manage_questions': 'Sualları idarə et',
        'add_question': 'Sual əlavə et',
        'edit_question': 'Sualı redaktə et',
        'delete_question': 'Sualı sil',
        'question_text': 'Sual mətni',
        'question_type': 'Sual növü',
        'multiple_choice': 'Çoxseçimli',
        'true_false': 'Doğru/Yanlış',
        'short_answer': 'Qısa cavab',
        'essay': 'Esse',
        'correct_answer': 'Düzgün cavab',
        'explanation': 'İzahat',
        'points': 'Xallar',
        'difficulty': 'Çətinlik',
        'difficulty_level': 'Çətinlik səviyyəsi',
        'easy': 'Asan',
        'medium': 'Orta',
        'hard': 'Çətin',
        'total_questions': 'Ümumi suallar',
        'question_created': 'Sual uğurla yaradıldı',
        'question_updated': 'Sual uğurla yeniləndi',
        'question_deleted': 'Sual uğurla silindi',
        'search_questions': 'Sual axtar',
        'no_questions_found': 'Sual tapılmadı',
        'question_options': 'Sual variantları',
        'add_option': 'Variant əlavə et',
        'option_text': 'Variant mətni',
        'is_correct': 'Düzgündür',
        'select_question_type': 'Sual növü seçin',
        'enter_question_text': 'Sual mətnini daxil edin',
        'enter_correct_answer': 'Düzgün cavabı daxil edin',
        'enter_explanation': 'İzahat daxil edin (istəyə bağlı)',
        'upload_image': 'Şəkil yüklə',
        'question_image': 'Sual şəkli',
        'bulk_import': 'Toplu idxal',
        'import_questions': 'Sualları idxal et',
        'select_file': 'Fayl seçin',
        'import_from_csv': 'CSV/Excel-dən idxal et',
        'questions_imported': 'Suallar uğurla idxal edildi',
        'import_failed': 'İdxal uğursuz oldu',
        'question_bank': 'Sual bankı',
        'observers': 'Müşahidəçilər',
        'manage_observers': 'Müşahidəçiləri idarə et',
        'observer_instructions': 'Müşahidəçilər bu mövzunu və sualları görə bilər, amma dəyişiklik edə bilməzlər.',
        'select_observer': 'Müşahidəçi seçin',
        'add_observer': 'Müşahidəçi əlavə et',
        'current_observers': 'Mövcud müşahidəçilər',
        'no_observers_assigned': 'Hələ müşahidəçi təyin edilməyib',
        'observer_added': 'Müşahidəçi uğurla əlavə edildi',
        'observer_removed': 'Müşahidəçi silindi',
        'observer_already_assigned': 'Müşahidəçi artıq əlavə edilib',
        'observer_select_prompt': 'Lütfən əvvəlcə müşahidəçini seçin',
        'observer_manage_forbidden': 'Müşahidəçiləri yalnız mövzu sahibi və administratorlar idarə edə bilər',

        # Grading / Qiymətləndirmə
        'grading': 'Qiymətləndirmə',
        'grade_exam': 'İmtahanı qiymətləndir',
        'pending_grading': 'Gözləyən qiymətləndirmə',
        'graded': 'Qiymətləndirildi',
        'grade': 'Qiymət',
        'score': 'Bal',
        'student_answer': 'Tələbə cavabı',
        'points_earned': 'Qazanılan xallar',
        'total_points': 'Ümumi xallar',
        'grading_completed': 'Qiymətləndirmə uğurla tamamlandı',
        'auto_graded': 'Avtomatik qiymətləndirildi',
        'manual_grading_required': 'Əl ilə qiymətləndirmə tələb olunur',

        # Results / Nəticələr
        'results': 'Nəticələr',
        'exam_results': 'İmtahan nəticələri',
        'my_results': 'Mənim nəticələrim',
        'view_results': 'Nəticələrə bax',
        'results_history': 'Nəticələr tarixçəsi',
        'passed': 'Keçdi',
        'failed': 'Keçmədi',
        'pending': 'Gözləyir',
        'not_passed': 'Keçmədi',
        'your_score': 'Sizin balınız',
        'total_score': 'Ümumi bal',
        'correct_answers': 'Düzgün cavablar',
        'incorrect_answers': 'Yanlış cavablar',
        'unanswered': 'Cavabsız',
        'time_taken': 'Sərf olunan vaxt',
        'exam_date': 'İmtahan tarixi',
        'attempt': 'Cəhd',
        'no_results': 'Nəticə yoxdur',
        'congratulations': 'Təbriklər!',
        'you_passed': 'Siz imtahandan keçdiniz',
        'you_failed': 'Təəssüf ki, imtahandan keçə bilmədiniz',
        'try_again': 'Yenidən cəhd edin',

        # Reports / Hesabatlar
        'reports': 'Hesabatlar',
        'analytics': 'Analitika',
        'exam_report': 'İmtahan hesabatı',
        'user_report': 'İstifadəçi hesabatı',
        'generate_report': 'Hesabat yarat',
        'export_pdf': 'PDF-ə ixrac et',
        'export_excel': 'Excel-ə ixrac et',
        'export_csv': 'CSV-yə ixrac et',
        'report_generated': 'Hesabat uğurla yaradıldı',
        'no_data': 'Məlumat yoxdur',
        'average_score': 'Orta bal',
        'highest_score': 'Ən yüksək bal',
        'lowest_score': 'Ən aşağı bal',
        'pass_rate': 'Keçid faizi',
        'completion_rate': 'Tamamlanma faizi',
        'attempts_count': 'Ümumi cəhdlər',

        # Settings / Parametrlər
        'settings': 'Parametrlər',
        'system_settings': 'Sistem parametrləri',
        'exam_settings_label': 'İmtahan parametrləri',
        'language_settings': 'Dil parametrləri',
        'system_language': 'Sistem dili',
        'language': 'Dil',
        'select_language': 'Sistem dilini seçin',
        'language_changed': 'Dil uğurla dəyişdirildi',
        'settings_updated': 'Parametrlər uğurla yeniləndi',
        'settings_failed': 'Parametrlər yadda saxlanılmadı',
        'default_exam_duration': 'Standart imtahan müddəti',
        'default_duration_minutes': 'İmtahan müddəti (dəqiqə)',
        'set_passing_score': 'İmtahandan keçmək üçün minimum balı təyin edin',
        'set_exam_duration': 'İmtahan üçün standart vaxt limitini təyin edin',
        'change_language': 'Sistem boyu istifadə olunan dili dəyişdirin',
        'save_passing_score': 'Keçid balını yadda saxla',
        'save_exam_duration': 'İmtahan müddətini yadda saxla',
        'save_language': 'Dili yadda saxla',
        'passing_score_updated': 'Keçid balı {value}%-ə yeniləndi',
        'exam_duration_updated': 'İmtahan müddəti {value} dəqiqəyə yeniləndi',
        'passing_score_range': 'Keçid balı 0 ilə 100 arasında olmalıdır',
        'duration_positive': 'İmtahan müddəti 0-dan böyük olmalıdır',
        'enter_valid_number': 'Düzgün rəqəm daxil edin',
        'students_need_score': 'Tələbələr imtahandan keçmək üçün bu bala ehtiyac duyurlar',
        'default_time_limit': 'İmtahanlar üçün standart vaxt limiti',

        # Email / E-poçt
        'email': 'E-poçt',
        'email_templates': 'E-poçt şablonları',
        'customize_email': 'İmtahan nəticələri üçün e-poçt bildirişlərini fərdiləşdirin',
        'template_type': 'Şablon növü',
        'template_language': 'Şablon dili',
        'passed_results': 'Keçmiş nəticələr',
        'failed_results': 'Keçməmiş nəticələr',
        'pending_grading': 'Gözləyən qiymətləndirmə',
        'email_subject': 'E-poçt mövzusu',
        'email_body': 'E-poçt mətni',
        'save_template': 'Şablonu yadda saxla',
        'reset_to_default': 'Standarta sıfırla',
        'test_email': 'E-poçtu test et',
        'template_saved': 'Şablon uğurla yadda saxlanıldı',
        'template_reset': 'Şablon standarta sıfırlandı',
        'template_not_found': 'Standart şablon tapılmadı',
        'test_email_opened': '{email} üçün test e-poçtu açıldı',
        'email_failed': 'E-poçt müştərisi açılmadı',
        'available_placeholders': 'Mövcud yertutucu',
        'subject_body_required': 'Mövzu və mətn boş ola bilməz',
        'enter_subject_body': 'Test etməzdən əvvəl mövzu və mətni daxil edin',

        # Profile / Profil
        'profile': 'Profil',
        'my_profile': 'Mənim profilim',
        'edit_profile': 'Profili redaktə et',
        'change_password': 'Şifrəni dəyişdir',
        'current_password': 'Cari şifrə',
        'new_password': 'Yeni şifrə',
        'confirm_password': 'Şifrəni təsdiq et',
        'password_updated': 'Şifrə uğurla yeniləndi',
        'password_mismatch': 'Şifrələr uyğun gəlmir',
        'incorrect_password': 'Cari şifrə yanlışdır',
        'profile_updated': 'Profil uğurla yeniləndi',

        # Exam Interface / İmtahan interfeysi
        'exam_interface': 'İmtahan interfeysi',
        'time_remaining': 'Qalan vaxt',
        'question': 'Sual',
        'of': '/',
        'mark_for_review': 'Yoxlamaq üçün işarələ',
        'marked_for_review': 'Yoxlamaq üçün işarələnib',
        'answered': 'Cavablandırılıb',
        'not_answered': 'Cavablandırılmayıb',
        'submit_exam': 'İmtahanı bitir',
        'confirm_submit': 'Təqdim etmək istədiyinizə əminsiniz?',
        'confirm_submit_message': 'Təqdim etdikdən sonra cavablarınızı dəyişə bilməyəcəksiniz.',
        'exam_submitted': 'İmtahan uğurla təqdim edildi',
        'your_answer': 'Sizin cavabınız',
        'select_answer': 'Cavabınızı seçin',
        'type_answer': 'Cavabınızı yazın',
        'true': 'Doğru',
        'false': 'Yanlış',
        'navigation': 'Naviqasiya',
        'save_continue': 'Yadda saxla və davam et',
        'skip_question': 'Sualı keç',
        'exam_auto_submit': 'Vaxt bitdi! İmtahan avtomatik təqdim ediləcək.',
        'time_warning': 'Diqqət: Yalnız {minutes} dəqiqə qalıb!',

        # Permissions / İcazələr
        'permissions': 'İcazələr',
        'assign_exam': 'İmtahan təyin et',
        'exam_permissions': 'İmtahan icazələri',
        'grant_access': 'Giriş ver',
        'revoke_access': 'Girişi ləğv et',
        'access_granted': 'Giriş uğurla verildi',
        'access_revoked': 'Giriş uğurla ləğv edildi',
        'assigned_users': 'Təyin edilmiş istifadəçilər',
        'available_users': 'Mövcud istifadəçilər',

        # View Switcher / Görünüş dəyişdirici
        'switch_view': 'Görünüşü dəyişdir',
        'admin_view': 'Admin görünüşü',
        'expert_view': 'Ekspert görünüşü',
        'hr_view': 'İK görünüşü',
        'examinee_view': 'İştirakçı görünüşü',

        # Roles / Rollar
        'admin_role': 'Administrator',
        'expert_role': 'Ekspert',
        'hr_role': 'İK meneceri',
        'examinee_role': 'İştirakçı',

        # Validation Messages / Təsdiqləmə mesajları
        'field_required': 'Bu xana tələb olunur',
        'invalid_email': 'Yanlış e-poçt ünvanı',
        'invalid_format': 'Yanlış format',
        'value_too_short': 'Dəyər çox qısadır',
        'value_too_long': 'Dəyər çox uzundur',
        'invalid_number': 'Yanlış rəqəm',
        'invalid_date': 'Yanlış tarix',

        # Confirmations / Təsdiqləmələr
        'are_you_sure': 'Əminsiniz?',
        'cannot_undo': 'Bu əməliyyat geri alına bilməz',
        'confirm_delete': 'Bu elementi silmək istədiyinizə əminsiniz?',
        'confirm_delete_user': 'Bu istifadəçini silmək istədiyinizə əminsiniz?',
        'confirm_delete_exam': 'Bu imtahanı silmək istədiyinizə əminsiniz?',
        'confirm_delete_question': 'Bu sualı silmək istədiyinizə əminsiniz?',

        # Notifications / Bildirişlər
        'operation_successful': 'Əməliyyat uğurla tamamlandı',
        'operation_failed': 'Əməliyyat uğursuz oldu',
        'changes_saved': 'Dəyişikliklər uğurla yadda saxlanıldı',
        'changes_discarded': 'Dəyişikliklər ləğv edildi',
        'no_changes': 'Yadda saxlanılacaq dəyişiklik yoxdur',

        # Date/Time / Tarix/Vaxt
        'today': 'Bu gün',
        'yesterday': 'Dünən',
        'tomorrow': 'Sabah',
        'date': 'Tarix',
        'time': 'Vaxt',
        'datetime': 'Tarix və Vaxt',
        'created_at': 'Yaradılma tarixi',
        'updated_at': 'Yenilənmə tarixi',
        'last_login': 'Son giriş',

        # Categories / Kateqoriyalar
        'category': 'Kateqoriya',
        'categories': 'Kateqoriyalar',
        'uncategorized': 'Kateqoriyasız',

        # PDF Export / PDF ixracı
        'pdf_export': 'PDF ixracı',
        'export_variants': 'Variantları ixrac et',
        'variant_count': 'Variant sayı',
        'generate_pdf': 'PDF yarat',
        'pdf_generated': 'PDF uğurla yaradıldı',
        'pdf_failed': 'PDF yaradılması uğursuz oldu',

        # Additional Question Management / Əlavə sual idarəetməsi
        'select_exam': 'Sual bazası statistikasını görmək üçün imtahan seçin',
        'select_topic': 'Mövzu seçin',
        'filter_by_type': 'Növə görə süz',
        'all_types': 'Bütün növlər',
        'image': 'Şəkil',
        'download_template': 'Şablonu yüklə',
        'export_questions': 'Sualları ixrac et',
        'new_topic': 'Yeni mövzu',
        'question_pool_config': 'Sual bazası konfiqurasiyası',
        'question_bank_overview': 'Sual bankına ümumi baxış',
        'not_used': 'İstifadə edilmir',
        'test_dialog': 'Test dialoqu',
        'add_new_question': 'Yeni sual əlavə et',
        'question_text_required': 'Sual mətni tələb olunur',
        'valid_numeric': 'Düzgün rəqəm daxil edin',
        'add_option_text': 'Variant əlavə et',
        'correct': 'Düzgün',
        'short_answer_question': 'Qısa cavab sualı',
        'essay_question': 'Esse sualı',
        'sample_answers': 'Qiymətləndirmə üçün nümunə cavablar və ya açar sözlər təqdim edin',
        'click_to_view': 'Tam ölçüdə görmək üçün şəklə klikləyin',
        'answer_options': 'Cavab variantları',
        'question_preview': 'Sualın önbaxışı',
        'confirm_delete_title': 'Silinməni təsdiq et',
        'select_questions_file': 'Suallar faylını seçin',
        'no_file_selected': 'Fayl seçilməyib',
        'template_downloaded': 'Şablon yükləndi',
        'no_questions_found_exam': 'Bu imtahanda sual tapılmadı',
        'questions_exported_title': 'Suallar ixrac edildi',
        'importing_questions': 'Suallar idxal edilir',
        'import_successful': 'İdxal uğurlu oldu',
        'import_failed_title': 'İdxal uğursuz oldu',
        'change_image': 'Şəkli dəyişdir',
        'remove_image': 'Şəkli sil',
        'no_image_selected': 'Şəkil seçilməyib',
        'upload_image_btn': 'Şəkil yüklə',
        'select_question_image': 'Sual şəklini seçin',
        'question_image_title': 'Sual şəkli',
        'edit_topic': 'Mövzunu redaktə et',
        'enter_descriptive_title': 'Təsviri başlıq daxil edin',
        'provide_instructions': 'İmtahan təlimatları və ya təsviri təqdim edin',
        'exam_title_required': 'İmtahan başlığı tələb olunur',
        'please_select_exam': 'Əvvəlcə imtahan seçin',
        'please_select_exam_questions': 'Sualları görmək üçün imtahan seçin',
        'view_question': 'Sualabax',
        'edit_question_tooltip': 'Sualı redaktə et',
        'delete_question_tooltip': 'Sualı sil',
        'number_symbol': '№',
        'english': 'English',
        'azerbaijani': 'Azərbaycan dili',
        'explanation_optional': 'İzahat (istəyə bağlı)',
        'sample_answer_label': 'Nümunə cavab / Açar sözlər (istəyə bağlı)',
        'pool_ready': 'Baza hazırdır',
        'pool_issue': 'Baza konfiqurasiya problemi',
        'points_greater_zero': 'Xallar 0-dan böyük olmalıdır',
        'error_saving_question': 'Sualı yadda saxlama xətası: {}',
        'error_uploading_image': 'Şəkil yükləmə xətası: {}',
        'file_size_too_large': 'Fayl ölçüsü çox böyükdür (maksimum {0}MB)',
        'invalid_file_type': 'Yanlış fayl növü. JPG, PNG və ya GIF şəkli seçin',
        'short_answer_help': 'Tələbələr qısa mətn cavabı yazacaqlar',
        'essay_help': 'Tələbələr daha uzun mətn cavabı yazacaqlar',
        'will_select_questions': '{1} mövcud sualdançı {0} sual seçiləcək',
        'available_count': '{0} mövcud',
        'requested_available': '{0}/{1}',
        'no_questions_found_exam_msg': 'Bu imtahan üçün sual tapılmadı',

        # Quiz Management / İmtahan idarəetməsi
        'create_assignment': 'Tapşırıq yarat',
        'manage_presets': 'Şablonları idarə et',
        'view_archived': 'Arxivlənmişlərə bax',
        'assignment_management': 'Tapşırıq idarəetməsi',
        'topic_title_required': 'Mövzu başlığı tələb olunur',
        'generating_pdfs': 'PDF-lər yaradılır...',
        'pdfs_generated_successfully': 'PDF-lər uğurla yaradıldı!',
        'open_folder': 'Qovluğu aç',
        'export_assignment': 'Tapşırığı PDF olaraq ixrac et',
        'variants_configured': 'Variantlar konfiqurasiya edildi',
        'this_will_generate': 'Bu yaradacaq:',
        'exam_paper': 'Hər variant üçün imtahan vərəqi',
        'answer_key': 'Hər variant üçün cavab açarı',

        # Reports / Hesabatlar
        'score_distribution': 'Bal paylanması',
        'pass_fail_trend': 'Keçid/Keçməmə tendensiyası',
        'question_difficulty_analysis': 'Sual çətinliyi analizi',
        'exam_performance': 'İmtahan performansı',
        'user_progress': 'İstifadəçi tərəqqisi',
        'question_analysis': 'Sual analizi',
        'detailed_analysis': 'İmtahan performansının ətraflı analizi',
        'individual_tracking': 'Fərdi istifadəçi performans izləməsi',
        'difficulty_performance': 'Sual çətinliyi və performans metrikaları',
        'key_performance_indicators': 'Əsas performans göstəriciləri',
        'performance_analytics': 'Performans analitikası',
        'detailed_reports': 'Ətraflı hesabatlar',
        'export_by_exam': 'İmtahana görə ixrac et',
        'export_by_student': 'Tələbəyə görə ixrac et',
        'select_student': 'Tələbə seçin',
        'choose_student': 'Tələbə seçin',
        'choose_exam': 'İmtahan seçin',
        'generate_pdf_report': 'PDF hesabat yarat',
        'filter_by_topic': 'Mövzuya görə süz',
        'filter_by_exam': 'İmtahan/Tapşırığa görə süz',
        'export_user_data': 'İstifadəçi məlumatlarını ixrac et',

        # Additional / Əlavə
        'scheduled': 'Planlaşdırılmış',
        'deadline': 'Son tarix',
        'shortcuts': 'Qısa yollar',
        'student': 'Tələbə',
        'submitted': 'Təqdim edilib',
        'completed': 'Tamamlanıb',
        'retake': 'Yenidən cəhd et',
        'not_specified': 'Göstərilməyib',

        # Reports - Additional / Hesabatlar - Əlavə
        'avg_exam_scores_over_time': 'Zamanla orta imtahan balları',
        'pass_rate_trend_over_time': 'Zamanla keçid faizi tendensiyası',
        'success_rate_by_difficulty': 'Çətinliyə görə uğur dərəcəsi',
        'success_rate': 'Uğur dərəcəsi',
        'sessions': 'Sessiyalar',
        'min_score': 'Min bal',
        'max_score': 'Maks bal',
        'avg_duration_min': 'Orta müddət (dəq)',
        'exam_sessions': 'İmtahan sessiyaları',
        'best_score': 'Ən yaxşı bal',
        'avg_duration': 'Orta müddət',
        'last_activity': 'Son fəaliyyət',
        'total_answers': 'Ümumi cavablar',
        'correct': 'Düzgün',
        'showing_questions_min_answers': 'Statistik etibarlılıq üçün ən azı 3 cavabı olan suallar göstərilir',
        'showing_all_questions': 'Bütün suallar göstərilir (3-dən az cavabı olanlar daxil)',
        'questions_low_success_review': '60%-dən az uğur dərəcəsi olan suallar yoxlanmalıdır',
        'all_topics': 'Bütün mövzular',
        'correct_answer': 'Düzgün cavab',
        'user_answer': 'İstifadəçi cavabı',
        'wrong': 'Yanlış',
        'correct_total': 'Düzgün/Ümumi',
        'correct_answers_count': 'Düzgün cavablar',
        'type': 'Növ',
        'result': 'Nəticə',
        'highest_score': 'Ən yüksək bal',
        'lowest_score': 'Ən aşağı bal',
        'total_active_exams': 'Ümumi aktiv imtahanlar',
        'total_completed_sessions': 'Ümumi tamamlanmış sessiyalar',
        'worst_score': 'Ən pis bal',
        'all_exams_assignments': 'Bütün imtahanlar/Tapşırıqlar',
        'departament': 'Departament',
        'exams_taken': 'Verilmiş imtahanlar',
        'never': 'Heç vaxt',
        'showing_all_questions_including': 'Bütün sualları göstər (az nümunəlilər daxil)',
        'create_preset_template': 'Şablon yarat',
        'changes': 'Dəyişikliklər',

        # PDF Export / PDF İxracı
        'export_pdf_reports': 'PDF Hesabatlarını İxrac Et',
        'export_by_exam': 'İmtahana Görə İxrac',
        'export_by_student': 'Tələbəyə Görə İxrac',
        'student_exam': "Tələbənin İmtahanı",
        'no_exams_for_report': 'Hesabat yaratmaq üçün imtahan yoxdur.',
        'no_students_completed': 'Tamamlanmış imtahanı olan tələbə tapılmadı.',
        'no_data_student_exam': 'Tələbə-imtahan hesabatları üçün məlumat yoxdur.',
        'select_exam_generate_pdf': 'Bütün tələbə performansları ilə ətraflı PDF hesabat yaratmaq üçün imtahan seçin:',
        'select_student_generate_pdf': 'Bütün imtahan nəticələri ilə ətraflı PDF hesabat yaratmaq üçün tələbə seçin:',
        'generate_pdf_report': 'PDF Hesabat Yarat',
        'created': 'Yaradılıb',
        'legacy': 'Köhnə',
        'exam_report': 'İmtahan Hesabatı',
        'student_report': 'Tələbə Hesabatı',
        'generated': 'Yaradılıb',
        'performance_summary': 'Performans Xülasəsi',
        'metric': 'Metrik',
        'value': 'Dəyər',
        'total_attempts': 'Ümumi Cəhdlər',
        'student_performance': 'Tələbə Performansı',
        'duration_min': 'Müddət (dəq)',
        'question_breakdown': 'Sual Təhlili',
        'question_details': 'Sual Təfərrüatları',
        'export_assignment_as_pdf': 'Tapşırığı PDF olaraq İxrac Et',
        'randomization_disabled': 'Qarışdırma deaktivdir. Bütün variantlar eyni olacaq.',
        'generating_variants': '{0} variant yaradılır...',
        'assignment': 'Tapşırıq',
        'questions': 'Suallar',
        'variants_configured': 'Variantlar konfiqurasiya edilib',
        'this_will_generate': 'Bu yaradacaq:',
        'exam_paper_each_variant': 'Hər variant üçün imtahan vərəqi',
        'answer_key_each_variant': 'Hər variant üçün cavab açarı',
        'files': 'Fayllar',
        'generate_pdfs': 'PDF-lər Yarat',
        'pdfs_generated_successfully': 'PDF-lər Uğurla Yaradıldı!',
        'variants_generated': '{0} variant yaradıldı',
        'location': 'Yer',
        'variant': 'Variant',
        'error_generating_pdfs': 'PDF yaratma xətası',
        'detailed_exam_report': 'Ətraflı İmtahan Hesabatı',
        'exam_summary': 'İmtahan Xülasəsi',
        'final_score': 'Yekun Bal',
        'passing_score': 'Keçid Balı',
        'duration': 'Müddət',
        'start_time': 'Başlama Vaxtı',
        'end_time': 'Bitmə Vaxtı',
        'question_by_question_breakdown': 'Sual-sual Təhlil',
        'option': 'Variant',
        'correct_answer_label': 'Düzgün Cavab',
        'student_selected': 'Tələbə Seçdi',
        'pass': 'KEÇDİ',
        'fail': 'KEÇMƏDİ',
        'minutes_label': 'dəqiqə',
        'special_warning': 'XÜSUSİ XƏBƏRDARLIQ',
        'confidential_text': 'Bu sənəd Azərbaycan Respublikasının Kosmik Agentliyinə (Azercosmos) aid məxfi məlumat ehtiva edir.',
        'page': 'Səhifə',
        'no_data': 'Məlumat Yoxdur',
        'no_completed_exam_session': 'Bu tələbə və imtahan üçün tamamlanmış imtahan sessiyası tapılmadı.',
        'pts': 'bal',
        'student_answer': 'Tələbə Cavabı',
        'no_answer_provided': 'Cavab verilməyib',
        'correct_uppercase': 'DÜZGÜN',
        'incorrect_uppercase': 'SƏHV',
        'file_saved': 'Fayl yadda saxlanıldı',
        'file_save_error': 'Fayl yadda saxlama xətası',
        'save_pdf_as': 'PDF-i belə saxla',
    }
}

# Current language setting
_current_language = 'en'

def set_language(language_code: str):
    """
    Set the current language for the application

    Args:
        language_code: Language code ('en' or 'az')
    """
    global _current_language
    if language_code in TRANSLATIONS:
        _current_language = language_code
    else:
        print(f"[WARNING] Unsupported language code: {language_code}. Defaulting to 'en'")
        _current_language = 'en'

def get_language():
    """Get the current language code"""
    return _current_language

def t(key: str, **kwargs) -> str:
    """
    Translate a key to the current language

    Args:
        key: Translation key
        **kwargs: Optional formatting arguments for string interpolation

    Returns:
        Translated string
    """
    translation = TRANSLATIONS.get(_current_language, {}).get(key, key)

    # Handle string interpolation if kwargs provided
    if kwargs:
        try:
            translation = translation.format(**kwargs)
        except KeyError as e:
            print(f"[WARNING] Missing placeholder in translation: {e}")

    return translation

def get_translations(language_code: str = None) -> dict:
    """
    Get all translations for a specific language

    Args:
        language_code: Language code (defaults to current language)

    Returns:
        Dictionary of translations
    """
    lang = language_code or _current_language
    return TRANSLATIONS.get(lang, TRANSLATIONS['en'])

def get_available_languages() -> list:
    """
    Get list of available language codes

    Returns:
        List of language codes
    """
    return list(TRANSLATIONS.keys())

def get_language_name(language_code: str) -> str:
    """
    Get the display name for a language code

    Args:
        language_code: Language code

    Returns:
        Display name for the language
    """
    names = {
        'en': 'English',
        'az': 'Azərbaycan dili'
    }
    return names.get(language_code, language_code)
